apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-end
  template:
    metadata:
      labels:
        app: back-end
    spec:
      containers:
      - name: backend
        image: 4587612/azure-back:test

        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  selector:
    app: back-end
  type: NodePort
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 31009
