version: '3'
services:
  app:
    image: 4587612/backend
    depends_on:
      - db
    build: .
    ports:
      - "3000:3000"
    
  db:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
